virtual-machine/create-vm-detailed/create-windows-vm-quick.ps1
virtual-machine/create-vm-dsc/create-windows-vm-iis-dsc.ps1
virtual-machine/create-vm-monitor-oms/create-windows-vm-detailed-oms.ps1
virtual-machine/encrypt-vm/encrypt-windows-vm.ps1

Updates for upcoming `New-AzureRmVm` experience

VM samples updates

---

storage/migrate-blobs-between-accounts/migrate-blobs-between-accounts.ps1

Not quite ready for review as script isn't finalized but I'm preparing the PR so it's easy to modify for when it is finalized.

Adding blob migration script.

---

sql-database/monitor-and-scale-pool/monitor-and-scale-pool.ps1

Fix is in response to user reported issue: https://github.com/MicrosoftDocs/azure-docs/issues/5047

updated scale elastic pool sample

---

storage/migrate-blobs-between-accounts/migrate-blobs-between-accounts.ps1

As per [customer issue](https://github.com/MicrosoftDocs/azure-docs/issues/6860) we were made aware that the script isn't utilizing synchcopy. As such I've modified the script so that it does so.

Upgrading script to use syncCopy

---

virtual-machine/create-vm-monitor-oms/create-windows-vm-detailed-oms.ps1

An unwanted backtick breaks a command.

Remove an unwanted backtick

---

hdinsight/create-cluster/create-cluster-with-config.ps1

Updated version to 3.6 (the latest HDI version)
Updated R Server portion to properly link RStudio once the cluster is deployed
Updated R Server portion to include necessary Spark config

Update create version to latest

---

app-service/deploy-ftp/deploy-ftp.ps1

Updated the xml portion of the script as the current script was erroring out.

(forumsteam) fixes MicrosoftDocs/azure-docs#11868

---

virtual-machine/encrypt-vm/encrypt-windows-vm.ps1

Updated the script for new parameters and use of key vault secrets

updated for new param and kv secrets

---

storage/post-storage-logs-to-log-analytics/PostStorageLogs2LogAnalytics.ps1

Add sample to post storage analytics logs to log analytics

Add sample to post storage analytics logs to log analytics

---

hdinsight/create-cluster/create-cluster.ps1

Fixing typo in comment:  storae -> storage

Fixes MicrosoftDocs/azure-docs#16513

---

api-management/backup-restore-apim-service/backup_restore_apim_service.ps1

Add the missing line for creating the blob container
- Update backupName to be valid (only dashes allowed)

(ForumsTeam) resolves MicrosoftDocs/azure-docs#17048

---

virtual-machine/create-wordpress-mysql/create-wordpress-mysql.ps1

Fixing typo in resource group name

(ForumsTeam) resolves MicrosoftDocs/azure-docs#19822

---

sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.ps1

This reverts commit eec79636810411b86fb94d5aed6b1b29f2adca76.

Revert "Changed PS Script (#162)"

---

application-gateway/waf-rules/waf-custom-rules.ps1

- [ x] PowerShell 5.1 on Windows
- [x ] PowerShell 6.x on Windows
- [ x] PowerShell 6.x on Linux
- [x ] Resources not created by the scripts in the pull request are __explicitly__ mentioned in a comment at the head of the file, __and__ have user-supplied variables or function arguments which correspond to the required resource identifiers.
- [x ] All user-supplied values are set in variables at the head of the file, after any comments.
- [ x] All passwords are user-supplied values, or generated by a secure random string generator.
- [x ] All Azure identifiers required to be universally unique are guaranteed to be so. 
- [x ] All scripts only use commands available in the latest release of the Azure PowerShell `Az` module. ([Command …

add waf custom rules

---

virtual-machine/copy-managed-disks-vhd-to-storage-account/copy-managed-disks-vhd-to-storage-account.ps1

added instructions for AzCopy

---

sql-database/import-from-bacpac/import-from-bacpac.ps1

http to https

---

virtual-machine/encrypt-vm/encrypt-windows-vm.ps1

fix Script for new AZ mod

---

.gitattributes

Add .gitattributes to fix CRLF issues
N/A

## Description

---

sql-database/failover-groups/add-single-db-to-failover-group-az-ps.ps1

did not test as nothing has been changed

found a typo

---

.github/pull_request_template.md

Link contributor guides in pull request template.
N/A

Link contributor guides in template

---

api-management/setup-rate-limit-policy/setup_rate_limit_policy.ps1

Fixes a sample for API Management as part of MicrosoftDocs/azure-docs#32963 
Platform: Cloudshell 
PSVersion: 6.2.2
PSEdition: Core
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
Az version: 2.5.0
Platform: Powershell 5.1 
PSVersion: 5.1.18362.145
PSEdition: Desktop
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion: 2.3
SerializationVersion: 2.3
WSManStackVersion: 3.0
Az version: 2.5.0

Ensure $context is set

---

sql-database/failover-groups/add-single-db-to-failover-group-az-ps.ps1

didn't test, just found a typo @sptramer #sign-off

another typo..

---

virtual-machine/copy-snapshot-to-storage-account/copy-snapshot-to-storage-account.ps1

Somehow a bunch of invalid characters got into this script. This PR removes them.
I tested the changes on the Azure cloudshell, script worked fine.

Removing invalid characters from script

---

sql-database/failover-groups/add-single-db-to-failover-group-az-ps.ps1

no testing was done, just fixing sentence structure in comments #sign-off @sptramer

fixed sentences

---

virtual-machine/create-managed-disk-from-snapshot/create-managed-disk-from-snapshot.ps1

Pulled in customer change and also fixed parameter for specifying the storage type.
Platform:
Local: 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145     
CloudShell:
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      2      2
Local: 
Major  Minor  Build  Revision
-----  -----  -----  --------
2      5      0      -1  
CloudShell:
2.6.0

Fix for PR #236

---

service-fabric/add-inbound-nsg-rule/add-inbound-nsg-rule.ps1

Removed the unnecessary line
Platform: Windows 10
Powershell version: 5.1.18362
Az version: 2.3.2

(AzureCXP) MicrosoftDocs/azure-docs#40387

---

virtual-machine/copy-managed-disks-vhd-to-storage-account/copy-managed-disks-vhd-to-storage-account.ps1

Checking on the option of using the azcopy command , it will create the unamanged disk as the name of the URL in the managed disk which will result in disk named abcd created.
I have this modification if you can added to the script so it will create the new VHD with the proper name .
if($useAzCopy -eq 1)
{
$containerSASURI = New-AzStorageContainerSASToken -Context $destinationContext -ExpiryTime(get-date).AddSeconds($sasExpiryDuration) -FullUri -Name $storageContainerName -Permission rw
$containername,$sastokenkey = $containerSASURI -split "?"
$containerSASURI = "$containername/$destinationVHDFileName`?$sastokenkey"
.\azcopy copy $sas.AccessSAS $containerSASURI
}
Platform:

change name of disk using azcopy

---

virtual-machine/create-snapshots-from-vhd-in-different-subscription/create-snapshots-from-vhd-in-different-subscription.ps1

https://github.com/MicrosoftDocs/azure-docs/issues/44624
Customer reported unexpected Â characters on lines 33 and 35 on Github issue: https://github.com/MicrosoftDocs/azure-docs/issues/44624
- [ x] Scripts do not contain static passwords or other secret tokens.
Platform:

Removed unexpected Â characters on lines 33 and 35

---

virtual-machine/encrypt-vm/encrypt-windows-vm.ps1

As per https://github.com/MicrosoftDocs/azure-docs/issues/44621
Platform:

(Azure CXP Team) corrected the sample script extra ')'

---

application-proxy/assign-group-to-app.ps1
application-proxy/assign-user-to-app.ps1
application-proxy/display-users-group-of-an-app.ps1
application-proxy/get-all-appproxy-apps-basic.ps1
application-proxy/get-all-appproxy-apps-by-connectorgroup.ps1
application-proxy/get-all-appproxy-apps-extended.ps1
application-proxy/get-all-appproxy-apps-with-policy.ps1
application-proxy/get-all-connectors.ps1
application-proxy/get-all-custom-domain-no-cert.ps1
application-proxy/get-all-custom-domains-and-certs.ps1
application-proxy/get-all-default-domain-apps.ps1
application-proxy/get-all-wildcard-apps.ps1
application-proxy/get-custom-domain-identical-cert.ps1
application-proxy/get-custom-domain-replace-cert.ps1
application-proxy/move-all-apps-to-a-connector-group.ps1

These new PowerShell script examples for Azure AD Application Proxy help customers get information about their Application Proxy apps and connector configuration, assign users/groups to Application Proxy apps, update certificates, and move Application Proxy connector groups. These scripts have been tested on PowerShell 5.1 (x64), modules AzureAD 2.0.2.52 and AzureADPreview 2.0.2.53. The requirements for Powershell version and modules are specified in each script. These scripts were not tested on PowerShell 6.x since the AzureAD and AzureADPreview modules are not supported on PS 6.x core. 
Related script wrapper articles and curated page: https://github.com/MicrosoftDocs/azure-docs-pr/pull/88965
Platform:
Az version: `(Get-InstalledModule …

New Application Proxy PowerShell sample scripts

---

application-proxy/get-all-appproxy-apps-with-policy.ps1

Updated the comments section to remove AzureAD module from the requirements, as this script requires the AzureADPreview module.
Non-code change: Testing not required.
Platform:

[Non-code change] Update requirements for Application Proxy script get-all-appproxy-apps-with-policy

---

data-factory/copy-from-azure-blob-to-blob/copy-from-azure-blob-to-blob.ps1

Updated Az commands to support ADF V2. Addressed the feedback[ 37039].(https://github.com/MicrosoftDocs/azure-docs/issues/37039)
Platform:

Updated Az commands to support ADF V2

---

virtual-machine-scale-sets/complete-scale-set/complete-scale-set.ps1

-AdminPassword parameter in Set-AzVmssOsProfile must be string.
-AdminPassword parameter in [Set-AzVmssOsProfile](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmssosprofile?view=azps-3.5.0) must be string.
This patch convert cred to string and put that into the parameter.
```
Set-AzVmssOsProfile
[-VirtualMachineScaleSet] <PSVirtualMachineScaleSet>
[[-ComputerNamePrefix] <String>]
[[-AdminUsername] <String>]
[[-AdminPassword] <String>]
[[-CustomData] <String>]
[[-WindowsConfigurationProvisionVMAgent] <Boolean>]
[[-WindowsConfigurationEnableAutomaticUpdate] <Boolean>]
[[-TimeZone] <String>]
[[-AdditionalUnattendContent] <AdditionalUnattendContent[]>]
[[-Listener] <WinRMListener[]>]
[[-LinuxConfigurationDisablePasswordAuthentication] <Boolean>]
[[-PublicKey] …
```

Fix invalid AdminPassword

---

cosmosdb/cassandra/ps-cassandra-create.ps1
cosmosdb/cassandra/ps-cassandra-list-get.ps1
cosmosdb/cassandra/ps-cassandra-ru-get.ps1
cosmosdb/cassandra/ps-cassandra-ru-update.ps1

This PR is for the Cassandra-specific samples.
Windows 10 1909 | WSL (Ubuntu 18.04) | 7.0.0 | 3.6.1

Cosmos DB - Cassandra samples

---

cosmosdb/common/ps-account-failover-priority-update.ps1
cosmosdb/common/ps-account-firewall-create.ps1
cosmosdb/common/ps-account-keys-connection-strings.ps1
cosmosdb/common/ps-account-update.ps1

This PR is for the Common cmdlet samples.

Cosmos DB - Common samples

---

cosmosdb/gremlin/ps-gremlin-create.ps1
cosmosdb/gremlin/ps-gremlin-list-get.ps1
cosmosdb/gremlin/ps-gremlin-ru-get.ps1
cosmosdb/gremlin/ps-gremlin-ru-update.ps1

This PR is for the Gremlin API cmdlet samples.

Cosmos DB - Gremlin samples

---

cosmosdb/mongodb/ps-mongodb-create.ps1
cosmosdb/mongodb/ps-mongodb-list-get.ps1
cosmosdb/mongodb/ps-mongodb-ru-get.ps1
cosmosdb/mongodb/ps-mongodb-ru-update.ps1

This PR is for the MongoDB API cmdlet samples.

Cosmos DB - MongoDB API samples

---

cosmosdb/table/ps-table-create.ps1
cosmosdb/table/ps-table-list-get.ps1
cosmosdb/table/ps-table-ru-get.ps1
cosmosdb/table/ps-table-ru-update.ps1

This PR is for the Table API cmdlet samples.

Cosmos DB - Table API samples

---

cosmosdb/sql/ps-account-firewall-create.ps1
cosmosdb/sql/ps-account-update.ps1
cosmosdb/sql/ps-container-create-index-none.ps1
cosmosdb/sql/ps-container-large-partition-key.ps1
cosmosdb/sql/ps-sql-account-failover-priority-update.ps1
cosmosdb/sql/ps-sql-create.ps1
cosmosdb/sql/ps-sql-list-get.ps1
cosmosdb/sql/ps-sql-ru-get.ps1
cosmosdb/sql/ps-sql-ru-update.ps1

This PR is for the SQL API cmdlet samples.

Cosmos DB - SQL samples

---

sql-database/managed-instance/create-and-configure-managed-instance.ps1

This script has been updated by srbozovi to use newer functions and such 
Platform: 
Windows 10 / ps 6.2.1 / az 2.4.0
windows 10 / ps 5.1.18362 / az 3.0.0

20200317 mifix

---

cosmosdb/common/ps-account-firewall-create.ps1
cosmosdb/common/ps-account-update-region.ps1

For Az.CosmosDB 0.1.4 release, update samples for account/common-focused cmdlets.

Cosmos DB | Update for Az.CosmosDB 0.1.4 | Common

---

cosmosdb/cassandra/ps-cassandra-create.ps1
cosmosdb/cassandra/ps-cassandra-list-get.ps1
cosmosdb/cassandra/ps-cassandra-ru-get.ps1
cosmosdb/cassandra/ps-cassandra-ru-update.ps1

Update samples to reflect changes in Az.CosmosDB 0.1.4 release. This PR is for Cassandra-specific samples.

Cosmos DB | Update for Az.CosmosDB 0.1.4 | Cassandra

---

cosmosdb/gremlin/ps-gremlin-create.ps1
cosmosdb/gremlin/ps-gremlin-ru-get.ps1
cosmosdb/gremlin/ps-gremlin-ru-update.ps1

Update samples to reflect changes in Az.CosmosDB 0.1.4 release. This PR is for Gremlin-specific samples.

Cosmos DB | Update for Az.CosmosDB 0.1.4 | Gremlin

---

cosmosdb/mongodb/ps-mongodb-ru-update.ps1

Update samples to reflect changes in Az.CosmosDB 0.1.4 release. This PR is for Mongo DB-specific samples.

Cosmos DB | Update for Az.CosmosDB 0.1.4 | MongoDB

---

cosmosdb/sql/ps-container-create-index-none.ps1
cosmosdb/sql/ps-container-large-partition-key.ps1
cosmosdb/sql/ps-sql-create.ps1
cosmosdb/sql/ps-sql-ru-update.ps1

Update samples to reflect changes in Az.CosmosDB 0.1.4 release. This PR is for SQL-specific samples.

Cosmos DB | Update for Az.CosmosDB 0.1.4 | SQL

---

cosmosdb/table/ps-table-create.ps1
cosmosdb/table/ps-table-ru-update.ps1

Update samples to reflect changes in Az.CosmosDB 0.1.4 release. This PR is for Table-specific samples.

Cosmos DB | Update for Az.CosmosDB 0.1.4 | Table

---

application-gateway/waf-rules/waf-custom-rules.ps1

Update to fix breaking change in New-AzApplicationGateway
OS BuildVersion   PSVersion    
-- ------------   ---------    
10.0.18362.752 5.1.18362.752
3.8.0
OS                           BuildVersion PSVersion
--                           ------------ ---------
Microsoft Windows 10.0.18363              7.0.0
3.8.0

fix breaking change

---

sql-database/restore-database/restore-database.ps1

Removed $restoreDatabaseName = "MySampleDatabase_GeoRestore" as it's not used
Added example for geo-restore

Added example for geo-restore based on CSS feedback.

---

azure-portal/dashboard-templates/portal-dashboard-template-testvm.json

Added azure dashboard sample template
Platform and PowerShell version: `Microsoft Windows 10.0.19041              7.0.3`
Az version: `4.4.0`

Added azure dashboard sample template

---

azure-portal/portal-dashboard-template-testvm.json

Updated portal dashboard template
Platform and PowerShell version: `Microsoft Windows 10.0.19041              7.0.3`
Az version: `4.4.0`

Updated portal dashboard template

---

app-service/backup-delete/backup-delete.ps1
app-service/backup-restore-diff-sub/backup-restore-diff-sub.ps1
app-service/backup-restore/backup-restore.ps1
app-service/deploy-github/deploy-github.ps1
devtest-lab/add-marketplace-images-to-lab/add-marketplace-images-to-lab.ps1
sql-database/import-from-bacpac/import-from-bacpac.ps1
virtual-machine/create-docker-host/create-docker-host.ps1
virtual-machine/create-vm-detailed/create-windows-vm-quick.ps1
virtual-machine/create-wordpress-mysql/create-wordpress-mysql.ps1
virtual-network/route-traffic-through-nva/route-traffic-through-nva.ps1
virtual-network/vm-with-two-nics/vm-with-two-nics.ps1

Updated examples to use correct cmdlet and parameters instead of aliases.
Fixed couple of issues in the app-services directory
OS                           BuildVersion PSVersion
--                           ------------ ---------
Microsoft Windows 10.0.18363              7.0.3
4.4.0

Fixed some examples

---

storage/post-storage-logs-to-log-analytics/PostStorageLogs2LogAnalytics.ps1

- Function Build-Signature was duplicated
- Variable ContainerName was not used
- Style fixed
Platform: `10.0.19041.1`
PowerShell version: `5.1.19041.1`
Az version: `4.4.0`

Removed duplicates and added use of global variable

---

cosmosdb/cassandra/ps-cassandra-autoscale.ps1
cosmosdb/gremlin/ps-gremlin-autoscale.ps1
cosmosdb/mongodb/ps-mongodb-autoscale.ps1
cosmosdb/sql/ps-sql-autoscale.ps1
cosmosdb/table/ps-table-autoscale.ps1

added autoscale throughput scripts
updated mongodb to include server version property in account create

add autoscale, server version to mongodb

---

sql-database/transparent-data-encryption/setup-tde-byok-sqlmi.ps1

Updating the script per PM Mladen Andzic

Update TDE BYOK script

---

cosmosdb/cassandra/ps-cassandra-autoscale.ps1
cosmosdb/cassandra/ps-cassandra-create.ps1
cosmosdb/gremlin/ps-gremlin-autoscale.ps1
cosmosdb/gremlin/ps-gremlin-create.ps1
cosmosdb/mongodb/ps-mongodb-autoscale.ps1
cosmosdb/mongodb/ps-mongodb-create.ps1
cosmosdb/sql/ps-container-create-index-none.ps1
cosmosdb/sql/ps-container-large-partition-key.ps1
cosmosdb/sql/ps-sql-autoscale.ps1
cosmosdb/sql/ps-sql-create.ps1
cosmosdb/table/ps-table-autoscale.ps1
cosmosdb/table/ps-table-create.ps1

Updating samples to use LocationObject which shows how to provision account with Availability Zone enabled regions.

Update cmdlets to show Availability Zone support

---

cosmosdb/cassandra/ps-cassandra-ru-migrate.ps1
cosmosdb/gremlin/ps-gremlin-ru-migrate.ps1
cosmosdb/mongodb/ps-mongodb-ru-migrate.ps1
cosmosdb/sql/ps-sql-ru-migrate.ps1
cosmosdb/table/ps-table-ru-migration.ps1

Adding throughput migration samples.

Add throughput migration samples

---

azure-migrate/migrate-at-scale-vmware-agentles/Initialize-AzMigrateReplicationInfrastructure.ps1

Script for initializing replication infrastructure for VMware agentless migrations
- [ x] This pull request was tested on __both of__:
- [ x] PowerShell 5.1 (Windows)
- [ x] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [ x] Scripts do not contain static passwords or other secret tokens.
- [ x] All Azure resource identifiers which must be universally unique are guaranteed to be so.

Initialize-AzMigrateReplicationInfrastructure.ps1

---

sql-database/restore-database/restore-database.ps1

i did not test, just fixing an incorrect value

Fixed typo

---

azure-migrate/automation-script/AzMigrate_CSV_Processor.ps1
azure-migrate/automation-script/AzMigrate_CleanUpTestMigration.ps1
azure-migrate/automation-script/AzMigrate_ClntScript.ps1
azure-migrate/automation-script/AzMigrate_Logger.ps1
azure-migrate/automation-script/AzMigrate_Shared.ps1
azure-migrate/automation-script/AzMigrate_StartMigration.ps1
azure-migrate/automation-script/AzMigrate_StartReplication.ps1
azure-migrate/automation-script/AzMigrate_StartTestMigration.ps1
azure-migrate/automation-script/AzMigrate_StopReplication.ps1
azure-migrate/automation-script/AzMigrate_Template.ps1
azure-migrate/automation-script/AzMigrate_UpdateMachineProperties.ps1
azure-migrate/automation-script/AzMigrate_UpdateReplicationStatus.ps1
azure-migrate/migrate-at-scale-vmware-agentles/Initialize-AzMigrateReplicationInfrastructure.ps1

PS automation

---

application-gateway/create-vmss/create-vmss.ps1

add -OsDiskCreateOption FromImage

---

backup/backup-encrypted-vm/backup-encrypted-vm.ps1

Correcting few command mistakes

---

application-proxy/get-all-appproxy-apps-extended.ps1

Updates from Arpad.

---

network-watcher/EnableRules.ps1

NPM Creation Script

---

application-management/export-all-app-registrations-secrets-and-certs.ps1

Adds app management and first sample script.

---

application-management/export-all-app-registrations-secrets-and-certs.ps1
application-management/export-all-enterprise-apps-secrets-and-certs.ps1
application-management/export-apps-with-expiring-secrets.ps1
application-management/export-apps-with-secrets-beyond-required.ps1

Adds additional scripts.

---

azure-migrate/dependencies-at-scale/AzMig_Dependencies.psm1

changes to the module including project v3 map

---

app-service/deploy-ftp/deploy-ftp.ps1

Change FTP script to accommodate for SSL
- [x ] PowerShell 7.x ([Latest PowerShell](https://github.com/PowerShell/PowerShell/releases))
- [x ] Scripts do not contain static passwords or other secret tokens.
- [x ] All Azure resource identifiers which must be universally unique are guaranteed to be so.

https://github.com/MicrosoftDocs/azure-docs/issues/48752

---

azure-migrate/migrate-at-scale-vmware-agentles/Agentless VMware automation/readme.md

This Pull Request replaces the correct url for Azure PowerShell Module Installation Guide on the following readme.md **https://github.com/Azure/azure-docs-powershell-samples/blob/master/azure-migrate/migrate-at-scale-vmware-agentles/Agentless%20VMware%20automation/readme.md**

replaced the correct url for the installation guide

---

virtual-machine-scale-sets/simple-scale-set/simple-scale-set.ps1

Converted example to using splatting instead of using line continuation characters per the PowerShell docs contribution guide.

Converted example to splatting per our contribution guide

---

network-watcher/EnableRules.ps1

Adding -n to the netstat switch to improve performance. Without this switch netstat will attempt to do DNS lookups for every connection which is slow.

Stop DNS lookup for netstat

---

container-registry/service-principal-create/service-principal-create.ps1

Fixes #363 - Updated sample for use with azps 7.x and higher.
Platform and PowerShell version:
Microsoft Windows 10.0.22000              7.2.1
Az version:
7.2.0

Updated sample for use with azps 7.x and higher

---

cosmosdb/mongodb/ps-mongodb-autoscale.ps1
cosmosdb/mongodb/ps-mongodb-create.ps1

Added enum values for server version 4.2 for MongoDB API
Reduced minimum max throughput for autoscale sample

update for mongo 4.2

---

sql-database/failover-groups/add-managed-instance-to-failover-group-az-ps.ps1

Switching from VPN gateway to global VNet peering

---

application-management/export-all-enterprise-apps-secrets-and-certs.ps1

Fixed case

---

app-service/configure-ssl-certificate/configure-ssl-certificate.ps1
app-service/map-custom-domain/map-custom-domain.ps1

Added an echo message to configure custom domain verification ID in the script
Platform and PowerShell version: Linux 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022              7.2.7
Az version: 9.1.0

add csuid note

---

app-service/backup-restore-diff-sub/backup-restore-diff-sub.ps1
app-service/backup-restore/backup-restore.ps1
app-service/deploy-deployment-slot/deploy-deployment-slot.ps1
app-service/deploy-local-git/deploy-local-git.ps1

added isManualIntegration property to fix OAuth errors
Platform and PowerShell version: Linux 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022              7.2.7
Az version: 9.1.0

add isManualIntegration property

---

sql-database/failover-groups/add-managed-instance-to-failover-group-az-ps.ps1

Typo "resouce"→"resource"
https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/failover-group-add-instance-tutorial?view=azuresql&tabs=azure-powershell
https://github.com/Azure/azure-docs-powershell-samples/blob/master/sql-database/failover-groups/add-managed-instance-to-failover-group-az-ps.ps1
#PingMSFTDocs

Typo "resouce"→"resource"

---

virtual-network/virtual-network-multi-tier-application/virtual-network-multi-tier-application.ps1

Existing setting results in error when script is ran.  Replaced with 2022 and was able to execute the script w/o errors. Changed value to: -Offer 'SQL2022-WS2022'

Changed offer for SQL server and Windows server.

---

api-management/setup-custom-domain/setup_custom_domain.ps1

resolves MicrosoftDocs/azure-docs#92378

(Azure CXP) sample fix using Set-AzApiManagement

---

sql-virtual-machine/get-sqliaasextension-healthstatus/GetSqlVirtualMachinesExtensionHealthStatus.psm1
sql-virtual-machine/get-sqliaasextension-healthstatus/ReportSqlVirtualMachinesExtensionHealthStatus.ps1

This script finds all SQL VMs currently running Full mode and gets the Extension Health status. At the end script will report the Extension Health status of each SQL VM in a subscription or list of subscriptions.
Platform and PowerShell version: 
OS: Microsoft Windows
BuildVersion: 10.0.22621.963
PSVersion: 5.1.22621.963
Az Version: 6.4.0
OS: Microsoft Windows
BuildVersion: 10.0.22621
PSVersion: 7.3.4
Az Version: 6.4.0

Add script to fetch SQL VM extension health status

---

README.md

Updated info about purpose of repo

Updated info about purpose of repo

---

README.md

Added archive schedule information
